# Generated by Django 3.2.16 on 2022-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_alter_playlist_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Moviess',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
