# Generated by Django 4.1.4 on 2022-12-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0015_auto_20221212_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related', through='playlists.PlaylistRelated', to='playlists.playlist'),
        ),
    ]
