# Generated by Django 3.2.16 on 2022-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_publish_timestamp_video_state_video_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url1',
            field=models.CharField(default='https://mega.nz/embed/CexREQpY#22QCIcvQ0NGEzoaF9Q_yqAqvxb_hhvTpZuTmuaTomoY', max_length=500),
        ),
    ]
