# Generated by Django 3.2.16 on 2022-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_video_url1'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url2',
            field=models.CharField(default='https://mega.nz/embed/CexREQpY#22QCIcvQ0NGEzoaF9Q_yqAqvxb_hhvTpZuTmuaTomoY', max_length=500),
        ),
    ]
