# Generated by Django 3.2.16 on 2022-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.ImageField(upload_to=None)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
    ]
